### PR TITLE
Shorten onKey function in RawKeyboardListener

### PR DESCRIPTION
**Pull request by stephenwade**

### CODE REVIEW

**Comment by josh-audio** [comment]
Did you test this? I can pull it locally, but if you know it's functionally equivalent then I'm not worried. I seem to remember having an issue where that flag was only set during keyboard shortcuts, but now I'm wondering if that was an assumption that I didn't actually check.

**Comment by stephenwade** [comment]
I tested this but it wouldn't hurt for you to test as well.

**Comment by josh-audio** [comment]
This is definitely working, but not functionally equivalent. The new code sets the status for each key that's pressed, where the old code only set them for ctrl/shift/alt.

This isn't a problem now since it's not causing a watchable state change. I do worry this would be a problem if the value were ever fed into a provider, since then it would be triggering re-renders on each keystroke for its listeners.

I don't currently have a good solution for this because I don't know the full problem space, but I'm hesitant to commit to this change right now for the same reason. The question is, will we ever want some visual state to change just because I pressed a modifier key? I'm not sure we will, but I'm not yet confident we won't.

**Comment by stephenwade** [comment]
I'd expect Provider to be smart enough to not notify if I set a variable to the same value it had before, but I'll play with it and see what its behavior is. I was thinking that this should be a Provider anyway.

In any case, if it does notify every time, then we can just change each of these lines to check the existing value before setting a new one.

> The question is, will we ever want some visual state to change just because I pressed a modifier key?

Yes, we probably want the cursor to change when a modifier key is pressed.

**Comment by josh-audio** [comment]
How smart it is actually depends on your implementation, but it can be figured out there I suppose. It feels like shuffling logic around but I don't mind you merging this. It requires more thought later either way.

**Review by josh-audio — APPROVED** [review]

**Pull request merged**
